package ActionServiceApp;


/**
* ActionServiceApp/ActionService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ActionService.idl
* Tuesday, April 2, 2019 11:08:40 PM EDT
*/

public interface ActionService extends ActionServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ActionService
