package ActionServiceApp;


/**
* ActionServiceApp/ActionServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ActionService.idl
* Monday, April 1, 2019 4:34:43 PM EDT
*/

abstract public class ActionServiceHelper
{
  private static String  _id = "IDL:ActionServiceApp/ActionService:1.0";

  public static void insert (org.omg.CORBA.Any a, ActionServiceApp.ActionService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ActionServiceApp.ActionService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ActionServiceApp.ActionServiceHelper.id (), "ActionService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ActionServiceApp.ActionService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ActionServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ActionServiceApp.ActionService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ActionServiceApp.ActionService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ActionServiceApp.ActionService)
      return (ActionServiceApp.ActionService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ActionServiceApp._ActionServiceStub stub = new ActionServiceApp._ActionServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ActionServiceApp.ActionService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ActionServiceApp.ActionService)
      return (ActionServiceApp.ActionService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ActionServiceApp._ActionServiceStub stub = new ActionServiceApp._ActionServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
