package ActionServiceApp;


/**
* ActionServiceApp/ActionServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ActionService.idl
* Monday, April 1, 2019 4:34:43 PM EDT
*/

public interface ActionServiceOperations 
{
  String addItem (String managerID, String itemID, String itemName, int quantity);
  String removeItem (String managerID, String itemID, int quantity);
  String listItemAvailability (String managerID);
  String borrowItem (String userID, String itemID, int numberOfDays);
  String waitList (String userID, String itemID, int numberOfDays);
  String findItem (String userID, String itemName);
  String returnItem (String userID, String itemID);
  boolean validateUser (String userID);
  String exchangeItem (String userID, String newItemID, String oldItemID);
} // interface ActionServiceOperations
